Pin eslint-plugin-rulesdir to v0.2.1
v0.2.2 fails with the following error:

  /home/runner/work/website/website/node_modules/gatsby/dist/utils/eslint-rules/limited-exports-page-templates.d.ts:1
  export {};
  ^^^^^^

  SyntaxError: Unexpected token 'export'
      at compileFunction (<anonymous>)
      at Object.compileFunction (node:vm:360:18)
      at wrapSafe (node:internal/modules/cjs/loader:1119:15)
      at Module._compile (node:internal/modules/cjs/loader:1155:27)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
      at Module.load (node:internal/modules/cjs/loader:1069:32)
      at Function.Module._load (node:internal/modules/cjs/loader:904:12)
      at Module.require (node:internal/modules/cjs/loader:1093:19)
      at require (node:internal/modules/cjs/helpers:108:18)
      at /home/runner/work/website/website/node_modules/eslint-plugin-rulesdir/index.js:42:37